### PR TITLE
Code Enhancement and Bug Fixes

### PR DESCRIPTION
**Pull request by Shivgupta1031**
**Changes Made:**

1. **Dependency and Gradle Upgrade:**
Updated all dependencies to their latest versions.
Upgraded Gradle version to the latest stable release.
Set targetSdk to version 34 for compatibility and to leverage the latest features.
(Issue #5 )

2. **UI Improvements:**
Made small adjustments to the UI of certain screens to enhance the overall user experience.

3. **Code Structure and Naming:**
Restructured and renamed files for improved code organization.
Enhancements made to increase code clarity and make it more understandable.

4. **AddContact Screen Implementation:**
Completed the implementation of the AddContact screen as per the specified task ( #1 ).

5. **Bug Fix: CallLogs Screen**
Resolved a bug (Issue #4) related to the opening of the CallLogs screen, ensuring smooth navigation and functionality.

6. **Unused Files Cleanup:**
Removed unnecessary and unused files from the project, reducing clutter and improving maintainability.

**Purpose:**
The purpose of this pull request is to enhance the overall quality and maintainability of the codebase. The changes aim to keep the project up-to-date with the latest dependencies, improve the user interface, and address specific tasks outlined in the project requirements. Additionally, bug fixes and code cleanup contribute to a more stable and efficient application.

**Any feedback, suggestions, or further improvements are welcome. Please review and merge at your earliest convenience.**

Thank you.

Best regards,
Shiv Kumar Gupta

### CODE REVIEW

**Comment by soumenkp2** [comment]
Hello Shiv, 
I am glad to see your contribution to make this project up to date. 
Yes I totally agree that this project consists of pretty old and low quality code. 
Thanks for putting up the contribution. 
I shall be reviewing the code at earliest and merging it up soon. 

Regards 
Soumen

**Comment by soumenkp2** [comment]
Hey @Shivgupta1031 
Kindly divert it to a new remote branch (you can name it anything related to your contribution) and raise a PR there instead of master-branch. 
Thanks

**Comment by surajpocketfm** [comment]
Hey @Shivgupta1031 great contribution!
@soumenkp2 I think there also need of removing unnecessary files from the commit.
@Shivgupta1031 it would be great if you could remove unnecessary files from the commit which are not changed or are system generated.

**Comment by Shivgupta1031** [comment]
Hello @soumenkp2 
Thank You For The Feedback!
I have removed the unnecessary Files and also made another branch named test : https://github.com/Shivgupta1031/Pehchaan-SH-Developer/tree/test

**Pull request closed without merging**
