### PR TITLE
Code Enhancement and Bug Fixes

### PR DESCRIPTION
**Pull request by Shivgupta1031**
Changes Made:

Dependency and Gradle Upgrade:
Updated all dependencies to their latest versions.
Upgraded Gradle version to the latest stable release.
Set targetSdk to version 34 for compatibility and to leverage the latest features.
(Issue https://github.com/soumenkp2/Pehchaan/issues/5 )

UI Improvements:
Made small adjustments to the UI of certain screens to enhance the overall user experience.

Code Structure and Naming:
Restructured and renamed files for improved code organization.
Enhancements made to increase code clarity and make it more understandable.

AddContact Screen Implementation:
Completed the implementation of the AddContact screen as per the specified task ( https://github.com/soumenkp2/Pehchaan/issues/1 ).

Bug Fix: CallLogs Screen
Resolved a bug (Issue https://github.com/soumenkp2/Pehchaan/issues/4) related to the opening of the CallLogs screen, ensuring smooth navigation and functionality.

Unused Files Cleanup:
Removed unnecessary and unused files from the project, reducing clutter and improving maintainability.

Purpose:
The purpose of this pull request is to enhance the overall quality and maintainability of the codebase. The changes aim to keep the project up-to-date with the latest dependencies, improve the user interface, and address specific tasks outlined in the project requirements. Additionally, bug fixes and code cleanup contribute to a more stable and efficient application.

Any feedback, suggestions, or further improvements are welcome. Please review and merge at your earliest convenience.

Thank you.

Best regards,
Shiv Kumar Gupta

### CODE REVIEW

**Comment by Shivgupta1031** [comment]
Hello @soumenkp2 , as asked I have created new PR From test branch!

**Comment by soumenkp2** [comment]
Kindly, divert it to dev remote branch

**Comment by Shivgupta1031** [comment]
DONE! @soumenkp2

**Comment by soumenkp2** [comment]
Good work @Shivgupta1031 , Merging it! Thanks:)

**Pull request merged**
